export const SEARCH_PERSON = 'SEARCH_PERSON';
export const GET_PERSON = 'GET_PERSON';
export const CLEAR_PERSONS = 'CLEAR_PERSONS';

export const SEARCH_COMPANY = 'SEARCH_COMPANY';
export const GET_COMPANY = 'GET_COMPANY';
export const CLEAR_COMPANIES = 'CLEAR_COMPANIES';

export const SEARCH_SOCIAL = 'SEARCH_SOCIAL';
export const GET_SOCIAL = 'GET_SOCIAL';
export const CLEAR_SOCIALS = 'CLEAR_SOCIALS';

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const GET_SERVICE = 'GET_SERVICE';
export const CLEAR_SERVICE = 'CLEAR_SERVICE';


export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
